export const communityGroups = [
  {
    id: 1,
    label: "Wonderful Westminster, MA",
    location: "42.5454, -71.8968",
    groupType: "Community/Town",
    membershipCount: 3400,
    groupCategory: "public",
  },
  {
    id: 2,
    label: "The Sutton Site",
    location: "42.1544, -71.7622",
    groupType: "Business",
    membershipCount: 670,
    groupCategory: "private",
  },
  {
    id: 3,
    label: "Attleboro, MA Community Resources Page",
    location: "41.9445, -71.2858",
    groupType: "Buy/Sell",
    membershipCount: 5300,
    groupCategory: "private",
  },
  {
    id: 4,
    label: "HAVERHILL MA 411",
    location: "42.7762, -71.0773",
    groupType: "Community/Town",
    membershipCount: 999,
    groupCategory: "private",
  },
  {
    id: 5,
    label: "Town of Westport, Ma. WE THE PEOPLE.",
    location: "41.6809, -71.1008",
    groupType: "Community/Town",
    membershipCount: 7600,
    groupCategory: "public",
  },
  {
    id: 6,
    label: "The Winchendon Residents Page",
    location: "42.6834, -72.0445",
    groupType: "Business",
    membershipCount: 890,
    groupCategory: "public",
  },
  {
    id: 7,
    label: "North Adams Chat",
    location: "42.6818, -73.1087",
    groupType: "Buy/Sell",
    membershipCount: 7605,
    groupCategory: "public",
  },
  {
    id: 8,
    label: "Hanson, Massachusetts Connect",
    location: "42.0843, -70.8348",
    groupType: "Community/Town",
    membershipCount: 4500,
    groupCategory: "public",
  },
  {
    id: 9,
    label: "Bellingham Buzz & Beyond",
    location: "42.0866, -71.4747",
    groupType: "Community/Town",
    membershipCount: 3500,
    groupCategory: "private",
  },
  {
    id: 10,
    label: "I Live in Taunton,MA",
    location: "41.9001, -71.0898",
    groupType: "Community/Town",
    membershipCount: 9300,
    groupCategory: "public",
  },
  {
    id: 11,
    label: "The West Bridgewater Hub",
    location: "42.0180, -71.0055",
    groupType: "Business",
    membershipCount: 5120,
    groupCategory: "public",
  },
  {
    id: 12,
    label: "Everything Greenfield MA",
    location: "42.5870, -72.6007",
    groupType: "Buy/Sell",
    membershipCount: 980,
    groupCategory: "private",
  },
  {
    id: 13,
    label: "Everything Abington, MA",
    location: "42.1056, -70.9454",
    groupType: "Community/Town",
    membershipCount: 5673,
    groupCategory: "public",
  },
  {
    id: 14,
    label: "Hanover Connect",
    location: "42.1141, -70.7972",
    groupType: "Community/Town",
    membershipCount: 560,
    groupCategory: "public",
  },
  {
    id: 15,
    label: "Hanson Ma Connection",
    location: "42.0938, -70.7987",
    groupType: "Community/Town",
    membershipCount: 3210,
    groupCategory: "public",
  },

  {
    id: 21,
    label: "Atlanta Connect",
    location: "42.0639, -70.7987",
    groupType: "Community/Town",
    membershipCount: 9007,
    groupCategory: "private",
  },
  {
    id: 22,
    label: "Florida US (Uncensored)",
    location: "42.1195, -70.9598",
    groupType: "Community/Town",
    membershipCount: 1001,
    groupCategory: "private",
  },
  {
    id: 23,
    label: "Beijing Close, Mass.",
    location: "42.1626, -71.0412",
    groupType: "Community/Town",
    membershipCount: 765,
    groupCategory: "public",
  },
  {
    id: 24,
    label: "Arsenal FC Stadium (WiE)",
    location: "42.2181, -70.9410",
    groupType: "Community/Town",
    membershipCount: 780,
    groupCategory: "private",
  },
  {
    id: 25,
    label: "New London Group",
    location: "41.6362, -70.9342",
    groupType: "Buy/Sell",
    membershipCount: 7601,
    groupCategory: "public",
  },
];
